new update comapy
tanvuongduc/HRM pull request #18
Opened 2021-06-01 07:57 UTC by 7un7un

2021-06-09 04:43 UTC, tanvuongduc requested changes

2021-06-09 04:43 UTC, tanvuongduc commented on frontend/src/Modules/Company/Components/Contact/Contact.js
> +import { Http } from '../../Shared/';
discard this

2021-06-09 04:43 UTC, tanvuongduc commented on frontend/src/Modules/Company/Components/Document/Document.js
> +                console.error('Error:', error);
should show a notify to user when got err

2021-06-09 04:43 UTC, tanvuongduc commented on frontend/src/Modules/Company/Components/Document/Document.js
> +    };
where is .then?

2021-06-09 04:43 UTC, tanvuongduc commented on frontend/src/Modules/Company/Components/Document/Document.js
> +                })
.then?

2021-06-09 04:43 UTC, tanvuongduc commented on frontend/src/Modules/Company/Components/Note/ModalAdd.js
>          position: 'absolute',
we dont use this any more. Should refactoring, move it to scss files

2021-06-09 04:43 UTC, tanvuongduc commented on frontend/src/Modules/Company/Components/Note/Note.js
> +    };
then?

2021-06-09 04:43 UTC, tanvuongduc commented on frontend/src/Modules/Company/Components/Note/_Note.scss
> +    box-shadow: 0px 2px 1px -1px gray, 0px 1px 1px 0px gray, 0px 1px 3px 0px gray;
if u using card in material UI, all of this already have

2021-06-09 04:43 UTC, tanvuongduc commented on frontend/src/Modules/Company/Components/Note/_Note.scss
> +                text-align: justify;
use flex box of material UI

2021-06-09 04:43 UTC, tanvuongduc commented on frontend/src/Modules/Company/Components/Note/_Note.scss
> +        justify-content: space-between;
use flex box of material UI

2021-06-09 04:43 UTC, tanvuongduc commented on frontend/src/Shared/Components/Upload/Upload.js
> +		const upload = await axios.post("http://103.138.108.104:3000/upload", formData)
what the hell

2021-06-09 04:43 UTC, tanvuongduc commented on frontend/src/Shared/Services/UtilService.js
> +        let url = "http://103.138.108.104:3000";
what the hell

2021-06-11 08:31 UTC, closed without merging

2021-06-11 08:37 UTC, 7un7un commented on frontend/src/Modules/Company/Components/Contact/Contact.js
> +import { Http } from '../../Shared/';
i will delete it

2021-06-11 08:39 UTC, 7un7un commented on frontend/src/Modules/Company/Components/Document/Document.js
> +                console.error('Error:', error);
use .then() ?

2021-06-11 08:40 UTC, 7un7un commented on frontend/src/Modules/Company/Components/Document/Document.js
> +    };
i will add it

2021-06-11 08:41 UTC, 7un7un commented on frontend/src/Modules/Company/Components/Note/ModalAdd.js
>          position: 'absolute',
agree

2021-06-11 08:42 UTC, 7un7un commented on frontend/src/Modules/Company/Components/Note/_Note.scss
> +    box-shadow: 0px 2px 1px -1px gray, 0px 1px 1px 0px gray, 0px 1px 3px 0px gray;
agree

2021-06-11 08:43 UTC, 7un7un commented on frontend/src/Shared/Components/Upload/Upload.js
> +		const upload = await axios.post("http://103.138.108.104:3000/upload", formData)
Trung trieu le write it, I'll fix it :v